// ── Kategori Listeleri ──────────────────────────────────────────────────────
export const kategoriler = [
  { id: 'cilt-bakimi', ad: 'Cilt Bakımı', ikon: '✨', aciklama: 'Nemlendirici, serum, maske ve daha fazlası' },
  { id: 'makyaj', ad: 'Makyaj', ikon: '💄', aciklama: 'Ruj, fondöten, far ve daha fazlası' },
  { id: 'parfum', ad: 'Parfüm', ikon: '🌸', aciklama: 'Eşsiz kokular koleksiyonu' },
  { id: 'sac-bakimi', ad: 'Saç Bakımı', ikon: '💇', aciklama: 'Şampuan, maske, serum ve bakım yağları' },
  { id: 'gunes-bakimi', ad: 'Güneş Koruyucu', ikon: '☀️', aciklama: 'SPF30, SPF50+ güneş koruma ürünleri' },
  { id: 'anne-bebek', ad: 'Anne & Bebek', ikon: '🍼', aciklama: 'Yeni doğandan itibaren hassas ciltler için' },
]

export const ciltBakimiKategorileri = [
  { id: 'nemlendirici', ad: 'Nemlendirici' },
  { id: 'serum', ad: 'Serum' },
  { id: 'gunes-kremi', ad: 'Güneş Kremi' },
  { id: 'temizleyici', ad: 'Temizleyici' },
  { id: 'goz-kremi', ad: 'Göz Kremi' },
  { id: 'tonik', ad: 'Tonik' },
  { id: 'maske', ad: 'Maske' },
  { id: 'peeling', ad: 'Peeling' },
]

export const makyajKategorileri = [
  { id: 'ruj', ad: 'Ruj' },
  { id: 'fondoten', ad: 'Fondöten' },
  { id: 'maskara', ad: 'Maskara' },
  { id: 'allik', ad: 'Allık' },
  { id: 'far', ad: 'Far' },
  { id: 'eyeliner', ad: 'Eyeliner' },
  { id: 'kapatici', ad: 'Kapatıcı' },
]

export const parfumKategorileri = [
  { id: 'kadin', ad: 'Kadın' },
  { id: 'erkek', ad: 'Erkek' },
  { id: 'unisex', ad: 'Unisex' },
]

export const sacBakimiKategorileri = [
  { id: 'sampuan', ad: 'Şampuan' },
  { id: 'sac-maskesi', ad: 'Saç Maskesi' },
  { id: 'sac-serumu', ad: 'Saç Serumu' },
  { id: 'sac-yagi', ad: 'Saç Yağı' },
  { id: 'sac-spreyi', ad: 'Sprey & Koruyucu' },
]

// ── Ürün Listesi — KALDIRILDI ────────────────────────────────────────────────
// Ürün verileri artık yalnızca Supabase'den gelir (getProducts / getProductById).
// Statik dizi silindi; bu yorum ileride arama sırasında yönlendirme sağlar.
const _kaldirildi = [

  // ── CİLT BAKIMI ─────────────────────────────────────────────────────────
  {
    id: 100,
    ad: 'Avene Hydrance Light SPF30 Nemlendirici Krem 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 1700,
    eskiFiyat: null,
    aciklama: 'Nemini kaybetmiş normal ve karma ciltler için nemlendirici krem. SPF30 koruma.',
    detay: 'Nemini kaybetmiş normal ve karma ciltler için nemlendirici krem. SPF30 güneş koruması sağlar. Avene termal suyu içerir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1000328/product/media/images/prod/PIM/20260128/13/e2b761dc-4687-4a5a-8489-1c9e6c83f344/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: 'En Favori',
  },
  {
    id: 102,
    ad: 'Topicrem Hydra+ Crème Teintée Éclat Medium 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 995,
    eskiFiyat: null,
    aciklama: 'Işıltı veren renkli nemlendirici krem. Medium ton.',
    detay: 'Krem formundaki yapısı sayesinde kolay uygulanır ve cilde hızla nüfuz ederek etkin bir şekilde nemlendirme sağlar. Işıltı veren renkli nemlendirici krem. Medium ton. Hyalüronik asit içerir, tüm gün nem sağlar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1800/prod/QC_ENRICHMENT/20251216/10/f14af82f-8851-30ce-8eb3-deaf7d956f00/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 105,
    ad: 'Topicrem Hydra+ Radiance Progressive Tan 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 835,
    eskiFiyat: null,
    aciklama: 'Kademeli bronzlaştırma etkili nemlendirici yüz kremi. Hyalüronik asit içerir.',
    detay: 'Kademeli bronzlaştırma etkili nemlendirici yüz kremi. Hyalüronik asit içerir. Cildi nemlendirir ve doğal bronz ton verir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1613/prod/QC/20241214/19/9c4c0a48-5b4a-3935-a3f6-3fe3eb1e6269/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 116,
    ad: 'Lumiderm Perfectage Krem 50g',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 750,
    eskiFiyat: null,
    aciklama: 'Onarıcı yaşlanma karşıtı yüz kremi. Hyalüronik asit içerir, paraben içermez.',
    detay: 'Onarıcı yaşlanma karşıtı yüz kremi. Hyalüronik asit içerir. Paraben içermez. Cildi yeniler ve sıkılaştırır.',
    gorsel: 'https://cdn.dsmcdn.com/ty1131/product/media/images/prod/SPM/PIM/20240113/19/61f4de4c-6410-357b-a5a3-018240ecb7d9/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: 'En Favori',
  },
  {
    id: 103,
    ad: 'Topicrem AC Purifying Cleansing Gel 200ml',
    kategori: 'cilt-bakimi',
    altKategori: 'temizleyici',
    fiyat: 800,
    eskiFiyat: null,
    aciklama: 'Yağlı ve karma ciltler için dengeleyici arındırıcı temizleme jeli. Salisilik asit içerir.',
    detay: 'Yağlı ve karma ciltler için dengeleyici arındırıcı temizleme jeli. Salisilik asit içerir. Cilt dengesini korur.',
    gorsel: 'https://cdn.dsmcdn.com/ty1801/prod/QC_ENRICHMENT/20251216/10/e2346480-8b1c-3fc2-9e1b-767c4be98eca/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 104,
    ad: 'Topicrem AH3 Global Anti-Aging Serum 30ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 1950,
    eskiFiyat: null,
    aciklama: 'Global yaşlanma karşıtı serum. Niacinamide içerir, hassas ciltlere uygundur.',
    detay: 'Global yaşlanma karşıtı serum. Niacinamide içerir. Hassas ciltlere uygundur. Kırışıklık ve leke karşıtı etki.',
    gorsel: 'https://cdn.dsmcdn.com/ty1801/prod/QC_ENRICHMENT/20251216/11/c0825c00-0a0c-3db9-9097-1e51237033cc/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: 'En Favori',
  },
  {
    id: 111,
    ad: 'Lumiderm Hyalo Niacinamide Cilt Serumu 20ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 950,
    eskiFiyat: null,
    aciklama: 'Niacinamide içerikli aydınlatıcı ve canlandırıcı cilt serumu.',
    detay: 'Niacinamide içerikli aydınlatıcı ve canlandırıcı cilt serumu. Gözenek görünümünü azaltır ve cilt tonunu eşitler.',
    gorsel: 'https://cdn.dsmcdn.com/ty1781/prod/QC_PREP/20251027/18/59af77e9-0b2f-3b89-8ee9-39fa74429632/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 129,
    ad: 'Lumiderm Hyalo C Aydınlatıcı ve Nemlendirici Cilt Serumu 20ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 1120,
    eskiFiyat: null,
    aciklama: 'C vitamini ve hyalüronik asit içeren aydınlatıcı ve nemlendirici cilt serumu.',
    detay: 'C vitamini ve hyalüronik asit içeren aydınlatıcı ve nemlendirici cilt serumu. Cilt tonunu eşitler, leke karşıtı etki sağlar ve cildi nemlendirir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1124/product/media/images/prod/SPM/PIM/20240106/17/9ccab9f3-b010-37df-a372-00c699a92dea/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 114,
    ad: 'Lumiderm Hyalo Peptide Yaşlanma Karşıtı Cilt Serumu 20ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 750,
    eskiFiyat: null,
    aciklama: 'Yaşlanma karşıtı ve nemlendirici cilt serumu. Hyalüronik asit içerir.',
    detay: 'Yaşlanma karşıtı ve nemlendirici cilt serumu. Hyalüronik asit içerir. Kırışıklıkları azaltır ve cildi sıkılaştırır.',
    gorsel: 'https://cdn.dsmcdn.com/ty1122/product/media/images/prod/SPM/PIM/20240106/17/4239e4ba-1146-3ce0-8caa-b258f4bc433c/1_org_zoom.jpg',
    puan: 4.5,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 106,
    ad: 'Eau Thermale Avène Termal Su 300ml',
    kategori: 'cilt-bakimi',
    altKategori: 'tonik',
    fiyat: 798,
    eskiFiyat: null,
    aciklama: 'Hassas ciltler için yatıştırıcı termal su spreyi. Anti-alerjik formül.',
    detay: 'Hassas ve tahrişe yatkın ciltler için özel olarak formüle edilmiştir. Zengin mineralli içeriği sayesinde cildi anında yatıştırır, kızarıklıkları azaltır ve ferahlık sağlar. Güneş sonrası, tıraş sonrası, makyaj sabitleyici ya da gün içinde nem desteği olarak kullanılabilir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1763/prod/QC_PREP/20250924/15/ae64b029-3a0a-3542-a2a0-f78b3217c62d/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: 'Çok Satan',
  },
  {
    id: 112,
    ad: 'Lumiderm Tonik 200ml',
    kategori: 'cilt-bakimi',
    altKategori: 'tonik',
    fiyat: 675,
    eskiFiyat: null,
    aciklama: 'Gözenek sıkılaştırıcı tonik. Hyalüronik asit içerir, tüm cilt tiplerine uygundur.',
    detay: 'Gözenek sıkılaştırıcı tonik. Hyalüronik asit içerir. Tüm cilt tiplerine uygundur. Cilt dokusunu düzenler.',
    gorsel: 'https://cdn.dsmcdn.com/ty1131/product/media/images/prod/SPM/PIM/20240113/19/29b9f02b-f97e-3b81-9ebc-1fc072dc97b8/1_org_zoom.jpg',
    puan: 4.5,
    yorumSayisi: 0,
    etiket: null,
  },

  // ── MAKYAJ ──────────────────────────────────────────────────────────────
  {
    id: 117,
    ad: 'PuroBIO Eyeshadow Powder 2.5gr No 22',
    kategori: 'makyaj',
    altKategori: 'far',
    fiyat: 335,
    eskiFiyat: null,
    aciklama: 'Işıltılı göz farı, beyaz ton. 2.5gr.',
    detay: 'Işıltılı göz farı, beyaz ton. 2.5gr. Doğal ve vegan formül. Uzun süreli kalıcılık.',
    gorsel: 'https://cdn.dsmcdn.com/ty535/product/media/images/20220917/18/176592900/572817050/1/1_org_zoom.jpg',
    puan: 4.5,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 118,
    ad: 'PuroBIO Eyeshadow Powder 2.5gr No 01',
    kategori: 'makyaj',
    altKategori: 'far',
    fiyat: 690,
    eskiFiyat: null,
    aciklama: 'Işıltılı göz farı, sarı ton. 2.5gr.',
    detay: 'Işıltılı göz farı, sarı ton. 2.5gr. Doğal ve vegan formül. Yoğun pigment.',
    gorsel: 'https://cdn.dsmcdn.com/ty1715/prod/QC_PREP/20250721/15/3093e4c3-52ce-3776-8f17-6e71fdbc7dbc/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 123,
    ad: 'PuroBIO 13 Eyeshadow',
    kategori: 'makyaj',
    altKategori: 'far',
    fiyat: 695,
    eskiFiyat: null,
    aciklama: 'Işıltılı göz farı, bordo/marsala ton.',
    detay: 'Işıltılı göz farı, bordo/marsala ton. Doğal ve vegan formül. Yoğun renk.',
    gorsel: 'https://cdn.dsmcdn.com/ty1707/prod/QC_PREP/20250711/14/d0dc098c-ebdc-31ea-af67-9a395ec30a66/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 119,
    ad: 'PuroBIO Face Duo Bronzer & Blush 02 Value Limited',
    kategori: 'makyaj',
    altKategori: 'allik',
    fiyat: 775,
    eskiFiyat: null,
    aciklama: 'Bronzer ve allık ikilisi. Altın ton, sınırlı seri.',
    detay: 'Bronzer ve allık ikilisi. Altın ton, sınırlı seri. İki ton bir pakette, doğal bronzluk etkisi.',
    gorsel: 'https://cdn.dsmcdn.com/ty1499/product/media/images/prod/QC/20240823/12/94f5b488-6608-39d1-be5b-d198d0fe69d5/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: 'Yeni',
  },
  {
    id: 120,
    ad: 'PuroBIO Bronzer & Allık',
    kategori: 'makyaj',
    altKategori: 'allik',
    fiyat: 895,
    eskiFiyat: null,
    aciklama: 'Mat finish bronzer ve allık. Çok renkli paket.',
    detay: 'Mat finish bronzer ve allık. Çok renkli paket. Doğal görünüm sağlar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1499/product/media/images/prod/QC/20240822/12/262fa7dd-9b3d-336d-a572-0febbf3867f9/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },

  // ── GÜNEŞ KORUYUCU ──────────────────────────────────────────────────────
  {
    id: 101,
    ad: 'SVR Sun Secure Güneş Koruyucu Stick SPF50+ 10g',
    kategori: 'gunes-bakimi',
    altKategori: 'gunes-kremi',
    fiyat: 395,
    eskiFiyat: null,
    aciklama: 'SPF50+ yüksek koruma faktörlü güneş koruyucu stick. Alkol içermez.',
    detay: 'SPF50+ yüksek koruma faktörlü güneş koruyucu stick. Alkol içermez. Hassas ciltlere uygundur.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/d80e6528-8088-3190-be62-7a57cf1cc438/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 108,
    ad: 'Pure By Lotus Doğal İçerikli Güneş Kremi SPF50 125ml',
    kategori: 'gunes-bakimi',
    altKategori: 'gunes-kremi',
    fiyat: 585,
    eskiFiyat: null,
    aciklama: 'Mineral filtreli, leke karşıtı, makyaj bazı olarak kullanılabilir güneş kremi. Paraben içermez.',
    detay: 'Mineral filtreli, leke karşıtı, makyaj bazı olarak kullanılabilir güneş kremi. Paraben içermez. Doğal ve vegan formül.',
    gorsel: 'https://cdn.dsmcdn.com/ty1498/product/media/images/prod/QC/20240823/12/d0f773b9-8177-316f-a3c0-e4d1d0efe041/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },

  // ── SAÇ BAKIMI ──────────────────────────────────────────────────────────
  {
    id: 107,
    ad: 'Lazartigue Thicker Hair Saç Dökülmesi Karşıtı Serum 50ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-serumu',
    fiyat: 3380,
    eskiFiyat: null,
    aciklama: 'Saç dökülmesine karşı güçlendirici serum. Tüm saç tiplerine uygundur.',
    detay: 'Saç dökülmesine karşı güçlendirici serum. Tüm saç tiplerine uygundur. Saç köklerini besler ve güçlendirir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1813/prod/QC_ENRICHMENT/20260116/17/84d834da-0d06-3986-b76e-af11868ff61f/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 115,
    ad: 'Lazartigue Serum d\'Exception Sıcaklığa Karşı Koruyucu Serum 50ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-serumu',
    fiyat: 2630,
    eskiFiyat: null,
    aciklama: 'Sıcaklığa karşı koruyucu güçlendirici saç serumu. Tüm saç tiplerine uygundur.',
    detay: 'Sıcaklığa karşı koruyucu güçlendirici saç serumu. Tüm saç tiplerine uygundur. Isıl işlemlerden saçı korur.',
    gorsel: 'https://cdn.dsmcdn.com/ty1813/prod/QC_ENRICHMENT/20260116/17/799acc69-5e48-3e1f-af40-c1ca0de1780d/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 109,
    ad: 'Lazartigue Huile Des Rêves Vegan Kuru Saç Bakım Yağı 50ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-yagi',
    fiyat: 2075,
    eskiFiyat: null,
    aciklama: 'Kuru saçlar için vegan kuru bakım yağı. Nemlendirici etki.',
    detay: 'Kuru saçlar için vegan kuru bakım yağı. Nemlendirici etki sağlar. Saçı besler ve parlaklık katar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/1c9ca72a-ec70-3eef-bc06-2dd8b516b668/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 110,
    ad: 'Cecemed Oily Hair Lotion Saç Bakım Losyonu 75ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-serumu',
    fiyat: 940,
    eskiFiyat: null,
    aciklama: 'Yağlı saçlar için özel saç bakım losyonu.',
    detay: 'Yağlı saçlar için özel saç bakım losyonu. Saç derisini dengeler ve yağlanmayı kontrol eder.',
    gorsel: 'https://cdn.dsmcdn.com/ty1536/product/media/images/ty1538/prod/QC/20240911/16/6f7ad963-1d84-3ef7-a48e-a044000ce0af/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 130,
    ad: 'Lazartigue Volumize Güçlendirici Kalınlaştırıcı Saç Spreyi 100ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-spreyi',
    fiyat: 2290,
    eskiFiyat: null,
    aciklama: 'İnce ve cansız saçlara hacim ve güç katan vegan saç spreyi.',
    detay: 'Saçı güçlendirmeye destek olur. Köklere ve uzunluklara 4 ile 5 kez püskürtün. İnce ve zayıf saçlar için özel olarak formüle edilmiştir. Vegan içerikli.',
    gorsel: 'https://cdn.dsmcdn.com/ty1813/prod/QC_ENRICHMENT/20260116/17/7fdea5b4-343e-38bb-a69f-b8c40690c512/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 113,
    ad: 'Lazartigue Exfoliate Vegan Saç Peelingi 75ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 2930,
    eskiFiyat: null,
    aciklama: 'Tüm saç tiplerine uygun vegan saç peelingi. Nemlendirici etki.',
    detay: 'Tüm saç tiplerine uygun vegan saç peelingi. Nemlendirici etki sağlar. Saç derisini arındırır ve yeniler.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/98dc1da2-6ef1-3fdb-871d-d47c56d1ccf5/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 121,
    ad: 'Lazartigue Curl Specialist Cream 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 2045,
    eskiFiyat: null,
    aciklama: 'Kıvırcık ve dalgalı saçlar için şekillendirici krem.',
    detay: 'Kıvırcık ve dalgalı saç tipleri için özel olarak formüle edilmiş, saçların doğal dalgalarını koruyan ve besleyen krem. Saçlara derinlemesine bakım yapar, ihtiyaç duydukları nemi sağlar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/4be849b0-656f-372e-b0eb-17dbecd4bee3/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 131,
    ad: 'Lazartigue Curl Specialist Rich Besleyici Nemlendirici Maske 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 3230,
    eskiFiyat: null,
    aciklama: 'Kıvırcık ve dalgalı saçlar için yoğun besleyici ve nemlendirici maske.',
    detay: 'Tüm saç tiplerine uygun formülüyle, her kullanıcıya hitap eder ve saçlara özel bakım sunar. Saçlara derinlemesine nüfuz eden yapısıyla daha parlak ve canlı görünmesine yardımcı olur.',
    gorsel: 'https://cdn.dsmcdn.com/ty1813/prod/QC_ENRICHMENT/20260116/17/db9af0e8-d493-3a84-9220-d580fe4c17b2/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 122,
    ad: 'Lazartigue Nourish Yoğun Besleyici Saç Kremi 150ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 2080,
    eskiFiyat: null,
    aciklama: 'Kuru ve yıpranmış saçlar için yoğun besleyici saç kremi.',
    detay: 'Kuru ve yıpranmış saçlar için yoğun besleyici saç kremi. Saçı besler, pürüzsüzleştirir.',
    gorsel: 'https://cdn.dsmcdn.com/ty1812/prod/QC_ENRICHMENT/20260116/17/3ead97a7-8b52-3a4e-a495-c2abec3eb412/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 132,
    ad: 'Lazartigue Nourish Yoğun Besleyici Şampuan 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sampuan',
    fiyat: 1330,
    eskiFiyat: null,
    aciklama: 'Kuru saçlar için yoğun besleyici vegan şampuan.',
    detay: 'Saçları derinlemesine besleyerek onarır ve güçlendirir, kuru saç tipleri için özel olarak formüle edilmiştir. Vegan içerikli formülü ile hayvan dostu bir bakım sunar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1813/prod/QC_ENRICHMENT/20260116/17/fcd4ffa2-d274-3c1d-b85a-3843dbada8cf/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 133,
    ad: 'Lazartigue Nourish High Yoğun Besleyici Maske 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 3430,
    eskiFiyat: null,
    aciklama: 'Kalın telli kuru saçlar için yoğun besleyici vegan saç maskesi.',
    detay: 'Kalın telli saçlar için özel olarak formüle edilmiş, saçların ihtiyaç duyduğu beslenmeyi sağlar. Vegan içerikli formülü ile hayvan dostu bir bakım sunar. Saçları derinlemesine besler ve onarır.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/29365863-fbd7-32bf-be02-ed9d3af1b1b5/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 134,
    ad: 'Lazartigue Nourish Light Besleyici Maske 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 2680,
    eskiFiyat: null,
    aciklama: 'İnce telli saçlara özel besleyici ve onarıcı vegan saç maskesi.',
    detay: 'İnce telli saçlara özel formülüyle, saçları derinlemesine besler ve onarır, sağlıklı bir görünüm kazandırır. Vegan içerikli yapısıyla hayvan dostu bir bakım sunar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/ddf6c805-701c-382a-83a1-1b32bc25e6fa/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 124,
    ad: 'Lazartigue Colour Protect Renk Koruyucu Vegan Saç Maskesi 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 3190,
    eskiFiyat: null,
    aciklama: 'Boyalı saçlar için renk koruyucu vegan saç maskesi.',
    detay: 'Tüm saç tiplerine uygun formülüyle, besleyici ve onarıcı etkisiyle saçların ihtiyaç duyduğu bakımı sağlar. Renk solmasını önler ve parlaklık katar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1814/prod/QC_ENRICHMENT/20260116/17/ee3e3c4a-6e67-3100-a664-3e0eb385fb03/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 125,
    ad: 'Lazartigue Repair Intensive Onarıcı Maske 250ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 3435,
    eskiFiyat: null,
    aciklama: 'Yıpranmış saçlar için yoğun onarıcı saç maskesi.',
    detay: 'İnce telli saçlar için özel olarak formüle edilmiş, saçları besleyici ve onarıcı etki sunar. Vegan içerikli formülüyle hayvan dostu bir bakım deneyimi sağlar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1812/prod/QC_ENRICHMENT/20260116/17/2ff9b664-0f1b-3e0b-9399-56e7dc570869/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 126,
    ad: 'Lazartigue Colour Protect Renk Koruyucu Vegan Saç Kremi 150ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 2345,
    eskiFiyat: null,
    aciklama: 'Boyalı saçlar için renk koruyucu vegan saç kremi.',
    detay: 'Boyalı saçlar için renk koruyucu vegan saç kremi. Rengi korur, saçı besler ve yumuşatır.',
    gorsel: 'https://cdn.dsmcdn.com/ty1537/product/media/images/ty1538/prod/QC/20240911/16/95ef8f91-7cb5-33f4-9285-5a2378cae067/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 127,
    ad: 'Lazartigue Anti-Dandruff Kepek Önleyici Saç Kremi 75ml',
    kategori: 'sac-bakimi',
    altKategori: 'sampuan',
    fiyat: 1345,
    eskiFiyat: null,
    aciklama: 'Kepek önleyici özel formüllü saç kremi.',
    detay: 'Kepek önleyici özel formüllü saç kremi. Kepek oluşumunu engeller ve saç derisini dengeler.',
    gorsel: 'https://cdn.dsmcdn.com/ty1537/product/media/images/ty1538/prod/QC/20240911/16/c356d02c-7af5-3580-9fbc-de0829bd30b6/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 128,
    ad: 'Lazartigue Repair Onarıcı Saç Kremi 150ml',
    kategori: 'sac-bakimi',
    altKategori: 'sac-maskesi',
    fiyat: 1395,
    eskiFiyat: null,
    aciklama: 'Tüm saç tiplerine uygun besleyici ve onarıcı saç kremi.',
    detay: 'Tüm saç tiplerine uygun besleyici ve onarıcı saç kremi. Saçı güçlendirir ve parlaklık katar.',
    gorsel: 'https://cdn.dsmcdn.com/ty1812/prod/QC_ENRICHMENT/20260116/17/77fe5d76-9889-308d-8e91-affc1952b550/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },

  // ── ANNE & BEBEK ────────────────────────────────────────────────────────
  {
    id: 135,
    ad: 'Topicrem Baby Moisturizing Milk 500ml',
    kategori: 'anne-bebek',
    altKategori: 'bebek-bakim',
    fiyat: 1180,
    eskiFiyat: null,
    aciklama: 'Hassas ve kuru ciltler için yeni doğan dahil bebek nemlendirici bakım sütü.',
    detay: 'Hassas ve kuru ciltler için özel olarak formüle edilmiş nemlendirici bakım sütü. Yeni doğan dahil her yaştaki bebek için uygundur. Koruyucu ve nemlendirici ajanlarla desteklenmiş formülü ile bebek cildini nazikçe nemlendirir ve korur.',
    gorsel: 'https://cdn.dsmcdn.com/ty1812/prod/QC_ENRICHMENT/20260116/16/64df7160-8eb8-39e8-a0d2-a481ae417637/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 136,
    ad: 'Topicrem Baby Ultra Nemlendirici Süt 200ml',
    kategori: 'anne-bebek',
    altKategori: 'bebek-bakim',
    fiyat: 800,
    eskiFiyat: null,
    aciklama: 'Hassas ve kuru bebek ciltleri için yüz ve vücut nemlendirici sütü.',
    detay: 'Hassas ve kuru ciltler için, yeni doğan dahil bebek yüz ve vücut nemlendiricisi. Cildi nazikçe nemlendirir ve korur. Dermatoloji testlerinden geçmiş, güvenli formül.',
    gorsel: 'https://cdn.dsmcdn.com/ty1801/prod/QC_ENRICHMENT/20251216/10/98330ad1-352d-3304-9724-8835182b11f7/1_org_zoom.jpg',
    puan: 0.0,
    yorumSayisi: 0,
    etiket: null,
  },

  // ── YENİ ÜRÜNLER (Trendyol yorumlarından eklendi) ──────────────────────────
  {
    id: 137,
    ad: 'Topicrem Calm Ar Anti-Redness Daily Cream 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 950,
    eskiFiyat: null,
    aciklama: 'Kızarıklık karşıtı günlük yüz bakım kremi. Hassas ve kızarıklığa eğilimli ciltler için.',
    detay: 'Kızarıklık karşıtı günlük yüz bakım kremi. Hassas ve kızarıklığa eğilimli ciltler için özel formül. Cildi sakinleştirir, kızarıklığı azaltır ve uzun süreli nem sağlar. Paraben ve renk maddesi içermez.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1801/prod/QC_ENRICHMENT/20251216/11/12106245-ac7b-3c6f-96d0-ac56c30bd3ec/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 138,
    ad: 'Dexeryl Emollient Cream Çok Kuru ve Atopiye Eğilimli Ciltler İçin Krem 500ml',
    kategori: 'cilt-bakimi',
    altKategori: 'vucut-kremi',
    fiyat: 650,
    eskiFiyat: null,
    aciklama: 'Çok kuru ve atopiye eğilimli ciltler için yoğun nemlendirici krem. 500ml.',
    detay: 'Çok kuru ve atopik cilt eğilimli ciltler için özel olarak geliştirilmiş emollient (yumuşatıcı) krem. Cildi derinlemesine nemlendirir, cilt bariyerini güçlendirir ve tahrişi önler. Koku ve renk maddesi içermez.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1689/product/media/images/prod/PIM/20250604/13/071edede-cfbc-43c8-a4b8-73e58d2bfab7/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 139,
    ad: 'SVR Densitium Baume Nuit 50ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 1500,
    eskiFiyat: null,
    aciklama: 'Yoğunlaştırıcı ve sıkılaştırıcı gece bakım balsamı. Yaşlanma karşıtı.',
    detay: 'Cilt yoğunluğunu ve elastikiyetini artıran gece bakım balsamı. Uyku sırasında cildi yeniler, sıkılaştırır ve besler. Hyalüronik asit ve peptit kompleksi içerir.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1801/prod/QC_ENRICHMENT/20251216/10/92bcae15-e56b-3abb-b1eb-3b0d4b6dd584/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 140,
    ad: 'Pella Luce Akne Karşıtı Yüz Temizleme Jeli',
    kategori: 'cilt-bakimi',
    altKategori: 'temizleyici',
    fiyat: 580,
    eskiFiyat: null,
    aciklama: 'Akne karşıtı yüz temizleme jeli. Yağlı ve akneye eğilimli ciltler için.',
    detay: 'Akneye eğilimli yağlı ciltler için formüle edilmiş yüz temizleme jeli. Gözenekleri temizler, sebum üretimini dengeler ve akne oluşumunu önler. Salisilik asit ve çay ağacı yağı içerir.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1641/prod/QC/20250226/14/7e32789f-17a8-3c91-b789-3e495f940171/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 141,
    ad: 'SVR Sebiaclear Micro-Peel Gözenek Sıkılaştırıcı Bakım Suyu 150ml',
    kategori: 'cilt-bakimi',
    altKategori: 'tonik',
    fiyat: 850,
    eskiFiyat: null,
    aciklama: 'Gözenek sıkılaştırıcı ve pürüzsüzleştirici bakım suyu. AHA+BHA içerir.',
    detay: 'Yüzey peeling etkili bakım suyu. AHA (glikolik asit) ve BHA (salisilik asit) içerir. Gözenekleri sıkılaştırır, cilt dokusunu düzenler ve parlak cilt görünümüne karşı savaşır.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1801/prod/QC_ENRICHMENT/20251216/10/74651cba-9aa2-3848-b1f1-11ff8070e663/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 142,
    ad: 'SVR Sebiaclear Az Ampul Flash 30ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 1200,
    eskiFiyat: null,
    aciklama: 'Yatıştırıcı leke karşıtı konsantre serum ampulü. Akne izleri için.',
    detay: 'Akne sonrası kızarıklık ve leke izlerini hedef alan konsantre serum. Niacinamide ve Bakuchiol içerir. Leke görünümünü azaltır, cilt tonunu eşitler ve cilt bariyerini onarır.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1802/prod/QC_ENRICHMENT/20251216/10/96ba255d-b946-3733-b53e-d5e4ee171faf/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 143,
    ad: 'SVR Sensifine Aqua Jel 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 780,
    eskiFiyat: null,
    aciklama: 'Hassas ciltler için hafif dokulu aqua jel nemlendirici. Koku içermez.',
    detay: 'Hassas ve reaktif ciltler için özel olarak formüle edilmiş hafif aqua jel. Cildi sakinleştirir, yoğun nem sağlar ve kızarıklık görünümünü azaltır. Koku, paraben ve alkol içermez.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1801/prod/QC_ENRICHMENT/20251216/10/84cf8a9f-62b9-3bda-98d9-77c630d645f6/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 144,
    ad: 'Topicrem Calm Ultra Moisturizing Soothing Cream 40ml',
    kategori: 'cilt-bakimi',
    altKategori: 'nemlendirici',
    fiyat: 950,
    eskiFiyat: null,
    aciklama: 'Ultra nemlendirici ve yatıştırıcı yüz kremi. Hassas ve reaktif ciltler için.',
    detay: 'Hassas, kuru ve reaktif ciltler için ultra nemlendirici ve yatıştırıcı krem. Prebiotic complex içerir, cilt bariyerini güçlendirir. Kızarıklık ve rahatsızlık hissini anında azaltır.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1801/prod/QC_ENRICHMENT/20251216/10/910a89ed-2e82-3d0b-92a0-4cc978b2598e/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 145,
    ad: 'Topicrem AC Purifying Cleansing Gel 400ml',
    kategori: 'cilt-bakimi',
    altKategori: 'temizleyici',
    fiyat: 1100,
    eskiFiyat: null,
    aciklama: 'Yağlı ve karma ciltler için arındırıcı temizleme jeli. 400ml ekonomik boy.',
    detay: 'Yağlı ve karma ciltler için arındırıcı temizleme jeli. 400ml ekonomik boy. Salisilik asit içerir, gözenekleri temizler ve cilt dengesini korur. Paraben ve sabun içermez.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1611/prod/QC/20241214/19/3cb4eebc-a93c-30f2-a2ca-589ea35a538a/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 146,
    ad: 'SVR Sebiaclear Cicapeel Cream 15ml',
    kategori: 'cilt-bakimi',
    altKategori: 'serum',
    fiyat: 850,
    eskiFiyat: null,
    aciklama: 'Akne izleri için onarıcı ve pürüzsüzleştirici krem. Cica + peeling.',
    detay: 'Akne sonrası izler ve cilt düzensizlikleri için onarıcı bakım kremi. Centella Asiatica (Cica) ve peeling aktifler içerir. Leke izlerini azaltır, cilt dokusunu düzenler.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1800/prod/QC_ENRICHMENT/20251216/10/77b39cd4-81e4-3645-8e6e-c32427660d5d/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
  {
    id: 147,
    ad: 'Bioderma Atoderm Intensive Baume Nemlendirici Bakım Kremi 500ml',
    kategori: 'cilt-bakimi',
    altKategori: 'vucut-kremi',
    fiyat: 750,
    eskiFiyat: null,
    aciklama: 'Çok kuru ve atopiye eğilimli ciltler için yoğun bakım balsamı. 500ml.',
    detay: 'Çok kuru ve atopiye eğilimli ciltler için geliştirilmiş yoğun bakım balsamı. Bioderma\'nın patentli teknolojisi ile cilt bariyerini güçlendirir, kaşıntıyı azaltır ve uzun süreli nem sağlar. Dermatoloji testlerinden geçmiştir.',
    gorsel: 'https://cdn.dsmcdn.com/mnresize/400/-/ty1000060/product/media/images/prod/PIM/20260126/08/1d6becd6-7802-4f68-9df5-d17b04429fae/1_org_zoom.jpg',
    puan: 5.0,
    yorumSayisi: 0,
    etiket: null,
  },
]

export const kategoriAdlari = {
  'cilt-bakimi': 'Cilt Bakımı',
  makyaj: 'Makyaj',
  parfum: 'Parfüm',
  'sac-bakimi': 'Saç Bakımı',
  'gunes-bakimi': 'Güneş Koruyucu',
  'anne-bebek': 'Anne & Bebek',
}

export const kategoriSayfaYollari = {
  'cilt-bakimi': '/cilt-bakimi',
  makyaj: '/makyaj',
  parfum: '/parfum',
  'sac-bakimi': '/sac-bakimi',
  'gunes-bakimi': '/gunes-koruyucu',
  'anne-bebek': '/anne-bebek',
}
